### ISSUE TITLE
prometheus configured with http (not s) gives weird error

### ISSUE THREAD

**Issue by bboreham** [weaveworks/service#1302]
I configured prometheus on my local machine for remote_write as follows:

```
global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

remote_write:
  - url: http://cloud.weave.works/api/prom/push
    basic_auth:
      password: <redacted>
```

run like this:

```
docker run -d --name=prom -p 9090:9090 -v /home/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
```

and observed the following errors in the Prometheus log:

```
time="2017-08-09T14:30:12Z" level=warning msg="Error sending 100 samples to remote storage: server returned HTTP status 400 Bad Request: snappy: corrupt input" source="queue_manager.go:500" 
```

changing the `http` to `https` makes it work.

It would be better if the error gave more of a hint what is wrong.
